#!/bin/sh
#reference: https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/history.zsh
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt append_history
setopt HIST_IGNORE_ALL_DUPS
setopt SHARE_HISTORY

# https://unix.stackexchange.com/questions/599641/why-do-i-have-duplicates-in-my-zsh-history
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
#setopt EXTENDED_GLOB # ==> see pg 81 of Learning Shell Scripting with ZSH

#setopt csh_null_glob # ==> see pg 80 of Learning Shell Scripting with ZSH
#setopt numericglobsort # ==> see pg 84 of Learning Shell Scripting with ZSH


