#!/bin/zsh
function mru_auto_cd() {
    cd $(dirname $(sed -E 's#(.*):.*:.*#\1#' <<< $1))
    git rev-parse --show-toplevel > /dev/null 2>&1 && cd $(git rev-parse --show-toplevel)
}

function mru(){
    # fzfresult=$(curl --silent http://localhost:2021 --max-time 0.05 --retry 4 | fzf --no-sort --exact \
    fzfresult=$( \
        wget --quiet --timeout=0.025 --tries=4 -O - http://localhost:2021 | \
        fzf --no-sort --exact \
        --preview '$DOTFILES/bin/preview.rb -v {1}' \
        --preview-window 'top:50%' \
        --header 'CTRL-o - open without abort(LESS) :: CTRL-s - toggle sort :: CTRL-g - toggle preview window' \
        --bind 'ctrl-s:toggle-sort,ctrl-g:toggle-preview,ctrl-o:execute:$DOTFILES/fzf/fhelp.sh $(sed -E '\''s#:\d+$##'\'' <<< {1}) > /dev/tty')

    if [[ ! -z $fzfresult ]]; then
        mru_auto_cd $fzfresult
        nvimcmd=$(sed -E 's/(.*):(.*):(.*)/nvim \1 '\''+call cursor(\2, \3)'\''/' <<< $fzfresult)
        eval "$nvimcmd '+lua vim.defer_fn(function() vim.api.nvim_call_function('\''CursorPing'\'', {}) end, 100)'"
    fi
}

alias 1m='mru'
alias removeMruInvalidEntries='curl http://localhost:2021/removeMruInvalidEntries'
