#!/bin/zsh
function serveeditor()(
    loadallifneeded
    cd ~/projects/tools/wm-local-http-static-server
    sudo -b npm start
)
function killeditor(){
    #kill with SIGINT=2 by default
    signal=${1:-2}
    echo killing with signal $signal
    sudo kill -$signal $(sudo lsof -i tcp:80 -t)
    sudo kill -$signal $(sudo lsof -i tcp:443 -t)
}

function sshci() {
    if [[ $# != 1 ]]; then
        echo 'usage: sshci $machine_ip'
        return 1
    fi
    ssh -i $HOME/.ssh/dev-server.pem ec2-user@$1 -p 22 -v
}

function Connect2AppsProdCluster() {
    gimme-aws-creds
    aws eks --region us-east-1 update-kubeconfig --name eks-prod
}

function Connect2AppsQACluster() {
    gimme-aws-creds
    aws eks --region eu-west-1 update-kubeconfig --name eks-qa
}

function Connect2AppsEUProdCluster() {
    gimme-aws-creds
    aws eks --region eu-central-1 update-kubeconfig --name eks-euprod
}

alias nolocal='[[ -f ~/walkme/settings.json ]] && mv ~/walkme/settings.json ~/walkme/_settings.json'
alias setlocal='[[ -f ~/walkme/_settings.json ]] && mv ~/walkme/_settings.json ~/walkme/settings.json'
