#!/usr/bin/env node
const fs = require('fs')
const args = process.argv.splice(2)
console.log(args)
const isInspectBrk = arg => /--inspect-brk/.test(arg)

const mochaHelperFile = {
    'dialog-processor':  '--file test/specs/helper.js',
    'player-sdk': '--file test/init.ts'
}
function inspectBrk() {
    if (args.find(isInspectBrk)) {
        return '--inspect-brk --timeout 99999999'
    }
    return ''
}
function getHelperFile() {
    const project = process.cwd().replace(/.*\/(.*)/, '$1')
    return mochaHelperFile[project] || ''
    switch(project) {
        case 'dialog-processor': 
            return '--file test/specs/helper.js'
    }
    return ''
}

function getOpts() {
    if(fs.existsSync(`${process.cwd()}/.mocharc`)) {
        return '--opts .mocharc'
    }
    return ''
}

function env() {
    const project = process.cwd().replace(/.*\/(.*)/, '$1')
    const TEST_MODE = 'TEST_MODE=true '
    if(project === 'player-sdk') {
        return `${TEST_MODE} TS_NODE_PROJECT=test/tsconfig.json `
    }
    return TEST_MODE
}

const cmd = `${env()} node node_modules/.bin/mocha ${inspectBrk()} ${getHelperFile()} ${getOpts()} ${args.filter(a => !isInspectBrk(a)).join(' ')}`
console.log(cmd)
require('child_process').execSync(cmd, {stdio: [0,1,2]})
